// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZjyYF1xmAd-pNYGmBkiVnBSoY2-DQm1E',
    appId: '1:1096957797241:web:caf45d24491d91955185a8',
    messagingSenderId: '1096957797241',
    projectId: 'moviesapp-9a4c6',
    authDomain: 'moviesapp-9a4c6.firebaseapp.com',
    storageBucket: 'moviesapp-9a4c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMaLpWySQpuodfpUuhz4R2RpYEWmKWSM',
    appId: '1:1096957797241:android:b65fe4fc38250bf65185a8',
    messagingSenderId: '1096957797241',
    projectId: 'moviesapp-9a4c6',
    storageBucket: 'moviesapp-9a4c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXwYZ33R6AAmqqbMgkObeg3INzWAbAypc',
    appId: '1:1096957797241:ios:7da46dfe4bb1387b5185a8',
    messagingSenderId: '1096957797241',
    projectId: 'moviesapp-9a4c6',
    storageBucket: 'moviesapp-9a4c6.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXwYZ33R6AAmqqbMgkObeg3INzWAbAypc',
    appId: '1:1096957797241:ios:89a9da5b19849f705185a8',
    messagingSenderId: '1096957797241',
    projectId: 'moviesapp-9a4c6',
    storageBucket: 'moviesapp-9a4c6.appspot.com',
    iosBundleId: 'com.example.moviesApp.RunnerTests',
  );
}
